version: "3.7"

services:
  api:
    image: beta/api:v1.2.0-beta
    container_name: "api"
    restart: always
    network_mode: "bridge"
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  client:
    image: beta/client:v1.2.0-beta
    container_name: "client"
    restart: always
    volumes:
      - D:\xx\go\go1\src\wrap\compose\client\config:/workdir/client/config
    network_mode: "bridge"
    ports:
      - "4000:4000"
    links:
      - api
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"